/**
 * Migration: initial schema
 *
 * Creates the core tables for Project Athena persistence:
 *   demos, use_cases, events, attacks, claude_usage, audit_log
 *
 * Compatible with both SQLite (dev) and PostgreSQL (production).
 */

exports.up = async function (knex) {
  // ── demos ──────────────────────────────────────────────────────────────────
  await knex.schema.createTable('demos', (t) => {
    t.string('id').primary();            // UUID generated by application
    t.string('okta_org').nullable();     // e.g. dev-12345.okta.com
    t.string('created_by').nullable();   // actor email / API key fingerprint
    t.timestamp('created_at').notNullable().defaultTo(knex.fn.now());
    t.timestamp('started_at').nullable();
    t.timestamp('reset_at').nullable();
    t.string('status').notNullable().defaultTo('idle'); // idle | active | reset
  });

  // ── use_cases ──────────────────────────────────────────────────────────────
  await knex.schema.createTable('use_cases', (t) => {
    t.string('id').primary();
    t.string('demo_id').notNullable().references('id').inTable('demos').onDelete('CASCADE');
    t.string('type').notNullable();         // mfaLogin, itpRiskElevation, …
    t.timestamp('completed_at').nullable();
    t.text('event_data').nullable();        // JSON string
    t.text('generated_content').nullable(); // JSON string (Claude output)
    t.index('demo_id');
    t.index('type');
  });

  // ── events ─────────────────────────────────────────────────────────────────
  await knex.schema.createTable('events', (t) => {
    t.string('id').primary();
    t.string('demo_id').notNullable().references('id').inTable('demos').onDelete('CASCADE');
    t.string('okta_uuid').nullable().unique(); // prevents duplicate processing
    t.string('event_type').notNullable();
    t.timestamp('received_at').notNullable().defaultTo(knex.fn.now());
    t.timestamp('event_timestamp').nullable(); // event.published
    t.text('event_data').nullable();           // JSON string
    t.index('demo_id');
    t.index('okta_uuid');
  });

  // ── attacks ────────────────────────────────────────────────────────────────
  await knex.schema.createTable('attacks', (t) => {
    t.string('id').primary();
    t.string('demo_id').notNullable().references('id').inTable('demos').onDelete('CASCADE');
    t.string('attack_type').notNullable();
    t.timestamp('launched_at').notNullable().defaultTo(knex.fn.now());
    t.timestamp('detection_triggered_at').nullable();
    t.string('target_use_case').nullable();  // which use case was triggered
    t.index('demo_id');
  });

  // ── claude_usage ───────────────────────────────────────────────────────────
  await knex.schema.createTable('claude_usage', (t) => {
    t.string('id').primary();
    t.string('demo_id').nullable().references('id').inTable('demos').onDelete('SET NULL');
    t.string('use_case_id').nullable().references('id').inTable('use_cases').onDelete('SET NULL');
    t.integer('tokens_in').notNullable().defaultTo(0);
    t.integer('tokens_out').notNullable().defaultTo(0);
    t.decimal('cost_usd', 10, 6).notNullable().defaultTo(0);
    t.string('model').notNullable();
    t.integer('latency_ms').nullable();
    t.timestamp('recorded_at').notNullable().defaultTo(knex.fn.now());
    t.index('demo_id');
    t.index('recorded_at');
  });

  // ── audit_log ──────────────────────────────────────────────────────────────
  await knex.schema.createTable('audit_log', (t) => {
    t.string('id').primary();
    t.string('actor').nullable();          // API key fingerprint or user email
    t.string('action').notNullable();      // start_demo, reset_demo, launch_attack, …
    t.string('resource').nullable();       // demo ID, attack type, etc.
    t.string('result').notNullable();      // success | failure
    t.text('details').nullable();          // JSON string
    t.timestamp('timestamp').notNullable().defaultTo(knex.fn.now());
    t.index('action');
    t.index('timestamp');
  });
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('audit_log');
  await knex.schema.dropTableIfExists('claude_usage');
  await knex.schema.dropTableIfExists('attacks');
  await knex.schema.dropTableIfExists('events');
  await knex.schema.dropTableIfExists('use_cases');
  await knex.schema.dropTableIfExists('demos');
};
