import { useState } from 'react';

export function ExecutiveBriefModal({ onClose }) {
  const [copied, setCopied] = useState(false);

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const briefText = `EXECUTIVE SECURITY BRIEF
Prepared by Okta AI — ${today}
Prepared for: Acme Corp

DEMO SUMMARY
During this demonstration, Okta's Identity Security Fabric detected 3 active threats, blocked 2 credential-based attacks, and automated 1 provisioning workflow — all in real-time with zero manual intervention.

KEY FINDINGS
1. Phishing-Resistant MFA: User authenticated with FIDO2 hardware key, eliminating credential theft risk. Breached password detection confirmed credentials are not in known breach databases.
2. Automated Provisioning: Group-based access assignment completed in under 2 seconds with full audit trail, replacing a manual workflow that typically takes 4-8 hours.
3. Impossible Travel Detection: Identity Threat Protection flagged a login from Tokyo 30 minutes after a NYC session — a physical impossibility indicating credential compromise.
4. Session Hijack Prevention: Cookie replay attack from a foreign IP was detected and blocked by ISPM before any data exfiltration occurred.

BUSINESS IMPACT
• Mean Time to Detect (MTTD): Reduced from 207 days (industry average) to < 3 seconds with continuous session evaluation
• Provisioning Efficiency: 99.7% reduction in access provisioning time (4-8 hours → 2 seconds)
• Compliance Coverage: Automated audit trail for SOX, SOC2, and GDPR access review requirements
• Risk Reduction: 3 attack vectors neutralized during this session alone

RECOMMENDED NEXT STEPS
1. Schedule a Proof of Value (POV) to connect your Okta tenant and see these detections with your own data
2. Integrate your SIEM/XDR via Shared Signals Framework (SSF) for unified threat intelligence
3. Enable Identity Threat Protection trial to baseline your organization's risk posture
4. Review ISPM findings against your current identity hygiene practices

Generated by Claude AI — Okta Identity Security Fabric`;

  const handleCopy = () => {
    navigator.clipboard.writeText(briefText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}>
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

      {/* Modal */}
      <div
        className="relative bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-8 py-5 rounded-t-2xl flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: '#3f59e4' }}>
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
              </svg>
            </div>
            <div>
              <h2 className="text-lg font-bold text-okta-dark">Executive Security Brief</h2>
              <p className="text-xs text-okta-medium-gray">Prepared by Okta AI</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-gray-100 transition-colors text-okta-medium-gray"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="px-8 py-6 space-y-6">
          {/* Meta */}
          <div className="flex items-center justify-between text-xs text-okta-medium-gray">
            <span>{today}</span>
            <span className="px-2.5 py-1 rounded-full bg-purple-100 text-purple-700 font-semibold">AI-Generated</span>
          </div>

          {/* Prospect */}
          <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
            <span className="text-xs font-semibold text-okta-medium-gray uppercase tracking-wider">Prepared for</span>
            <p className="text-lg font-bold text-okta-dark mt-1">Acme Corp</p>
          </div>

          {/* Demo Summary */}
          <div>
            <h3 className="text-sm font-bold text-okta-dark uppercase tracking-wider mb-2">Demo Summary</h3>
            <p className="text-sm text-gray-700 leading-relaxed">
              During this demonstration, Okta's Identity Security Fabric detected <strong>3 active threats</strong>, blocked <strong>2 credential-based attacks</strong>, and automated <strong>1 provisioning workflow</strong> — all in real-time with zero manual intervention.
            </p>
          </div>

          {/* Key Findings */}
          <div>
            <h3 className="text-sm font-bold text-okta-dark uppercase tracking-wider mb-3">Key Findings</h3>
            <div className="space-y-3">
              {[
                { icon: '🔐', title: 'Phishing-Resistant MFA', text: 'User authenticated with FIDO2 hardware key, eliminating credential theft risk. Breached password detection confirmed credentials are not in known breach databases.' },
                { icon: '⚡', title: 'Automated Provisioning', text: 'Group-based access assignment completed in under 2 seconds with full audit trail, replacing a manual workflow that typically takes 4-8 hours.' },
                { icon: '🌍', title: 'Impossible Travel Detection', text: 'Identity Threat Protection flagged a login from Tokyo 30 minutes after a NYC session — a physical impossibility indicating credential compromise.' },
                { icon: '🛡️', title: 'Session Hijack Prevention', text: 'Cookie replay attack from a foreign IP was detected and blocked by ISPM before any data exfiltration occurred.' },
              ].map((finding, i) => (
                <div key={i} className="flex gap-3 bg-blue-50 rounded-lg p-3 border border-blue-100">
                  <span className="text-lg flex-shrink-0">{finding.icon}</span>
                  <div>
                    <p className="text-xs font-bold text-okta-dark">{finding.title}</p>
                    <p className="text-xs text-gray-600 mt-0.5 leading-relaxed">{finding.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Business Impact */}
          <div>
            <h3 className="text-sm font-bold text-okta-dark uppercase tracking-wider mb-3">Business Impact</h3>
            <div className="grid grid-cols-2 gap-3">
              {[
                { metric: '< 3s', label: 'Mean Time to Detect', detail: 'vs. 207 days industry avg' },
                { metric: '99.7%', label: 'Provisioning Time Reduction', detail: '4-8 hours → 2 seconds' },
                { metric: '3', label: 'Attack Vectors Neutralized', detail: 'During this session' },
                { metric: '100%', label: 'Audit Trail Coverage', detail: 'SOX, SOC2, GDPR ready' },
              ].map((stat, i) => (
                <div key={i} className="bg-gray-50 rounded-xl p-4 border border-gray-200 text-center">
                  <p className="text-2xl font-bold" style={{ color: '#3f59e4' }}>{stat.metric}</p>
                  <p className="text-xs font-semibold text-okta-dark mt-1">{stat.label}</p>
                  <p className="text-xs text-okta-medium-gray mt-0.5">{stat.detail}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Next Steps */}
          <div>
            <h3 className="text-sm font-bold text-okta-dark uppercase tracking-wider mb-3">Recommended Next Steps</h3>
            <div className="space-y-2">
              {[
                'Schedule a Proof of Value (POV) to connect your Okta tenant and see these detections with your own data',
                'Integrate your SIEM/XDR via Shared Signals Framework (SSF) for unified threat intelligence',
                'Enable Identity Threat Protection trial to baseline your organization\'s risk posture',
                'Review ISPM findings against your current identity hygiene practices',
              ].map((step, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white flex-shrink-0" style={{ backgroundColor: '#3f59e4' }}>{i + 1}</span>
                  <p className="text-xs text-gray-700 leading-relaxed pt-1">{step}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-white border-t border-gray-200 px-8 py-4 rounded-b-2xl flex items-center justify-between">
          <span className="text-xs text-okta-medium-gray">Generated by Claude AI — Okta Identity Security Fabric</span>
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-white transition-all"
            style={{ backgroundColor: copied ? '#00A870' : '#3f59e4' }}
          >
            {copied ? (
              <>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7"/>
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"/>
                </svg>
                Copy to Clipboard
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
